// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7r9Z3sDO_aqjZNGSoi6jVAfSrDt-wFys',
    appId: '1:578732094610:web:d11867f5b450935dea624b',
    messagingSenderId: '578732094610',
    projectId: 'marketplace-8d6bd',
    authDomain: 'marketplace-8d6bd.firebaseapp.com',
    storageBucket: 'marketplace-8d6bd.firebasestorage.app',
    measurementId: 'G-PSMMLD2YM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIq5PmSYN_bmDFLnPL9ctTM06sM0nsUPM',
    appId: '1:578732094610:android:e3d33c8d33a21bdbea624b',
    messagingSenderId: '578732094610',
    projectId: 'marketplace-8d6bd',
    storageBucket: 'marketplace-8d6bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPDJs0A6XwKDvC5no7NcSo1-UkkZPfgw',
    appId: '1:578732094610:ios:559ba8ba1329223dea624b',
    messagingSenderId: '578732094610',
    projectId: 'marketplace-8d6bd',
    storageBucket: 'marketplace-8d6bd.firebasestorage.app',
    iosBundleId: 'com.example.foodMarketplaceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPDJs0A6XwKDvC5no7NcSo1-UkkZPfgw',
    appId: '1:578732094610:ios:559ba8ba1329223dea624b',
    messagingSenderId: '578732094610',
    projectId: 'marketplace-8d6bd',
    storageBucket: 'marketplace-8d6bd.firebasestorage.app',
    iosBundleId: 'com.example.foodMarketplaceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7r9Z3sDO_aqjZNGSoi6jVAfSrDt-wFys',
    appId: '1:578732094610:web:0d1bdf0e5fb7f54dea624b',
    messagingSenderId: '578732094610',
    projectId: 'marketplace-8d6bd',
    authDomain: 'marketplace-8d6bd.firebaseapp.com',
    storageBucket: 'marketplace-8d6bd.firebasestorage.app',
    measurementId: 'G-EL0Y00XVYV',
  );
} 